import { collectFunctionSpans } from '../src/parsers/unified_pipeline';
import { collectScannerSpans } from '../src/parsers/scanner';
import { collectTaxonomySpans } from '../src/parsers/taxonomy';
import { collectDelimiterSpans } from '../src/parsers/delimiters';
import { collectVariableSpans } from '../src/parsers/variable_hash';
import { findUnitSpans, collectUnitSpans } from '../src/parsers/units';
import { findDifferentialSpans, collectDifferentialSpans } from '../src/parsers/differentials';
import { findDimensionlessSpans, collectDimensionlessSpans } from '../src/parsers/dimensionless';
import { findBoundarySpans } from '../src/parsers/differentials';
import { collectBraKetDelimiterSpans } from '../src/parsers/braket';
import { collectSingleConstantSpans } from '../src/parsers/constants';
import { findOpaqueRanges } from '../src/parsers/unified_pipeline';
import { DEFAULT_COLORS, DEFAULT_OPTIONS } from '../src/config';

const body = "\n12                                   /3  \n";
console.log("1. findUnitSpans");
const unitSpans = findUnitSpans(body);
console.log("2. findDifferentialSpans");
const diffSpans = findDifferentialSpans(body);
console.log("3. findDimensionlessSpans");
const dimSpans = findDimensionlessSpans(body);
console.log("4. findBoundarySpans");
const boundarySpans = findBoundarySpans(body);
console.log("5. collectFunctionSpans");
collectFunctionSpans(body, DEFAULT_COLORS, new Set(), DEFAULT_OPTIONS);
console.log("6. collectScannerSpans");
collectScannerSpans(body, DEFAULT_COLORS);
console.log("7. collectUnitSpans");
collectUnitSpans(body, DEFAULT_COLORS, unitSpans);
console.log("8. collectDifferentialSpans");
collectDifferentialSpans(body, DEFAULT_COLORS, diffSpans, DEFAULT_OPTIONS);
console.log("9. collectDimensionlessSpans");
collectDimensionlessSpans(body, DEFAULT_COLORS, dimSpans);
console.log("10. collectBraKetDelimiterSpans");
collectBraKetDelimiterSpans(body, DEFAULT_COLORS);
console.log("11. collectSingleConstantSpans");
collectSingleConstantSpans(body, DEFAULT_COLORS);
console.log("12. collectDelimiterSpans");
collectDelimiterSpans(body, { forLatexWrap: false, palette: DEFAULT_OPTIONS.rainbowColors, includeBareBraces: true, highlightUnmatched: true });
console.log("13. collectTaxonomySpans");
collectTaxonomySpans(body, DEFAULT_COLORS, unitSpans, diffSpans, dimSpans, DEFAULT_OPTIONS);
console.log("14. collectVariableSpans");
collectVariableSpans(body, undefined, unitSpans, diffSpans, dimSpans, new Set(), boundarySpans);
console.log("15. findOpaqueRanges");
findOpaqueRanges(body);
console.log("ALL SUBPARSERS DONE!");
